# Generated by Django 4.1.7 on 2023-03-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_in_min',
            field=models.IntegerField(null=True),
        ),
    ]
