# Generated by Django 4.1.7 on 2023-03-15 18:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_movie_duration_in_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10), django.core.validators.MinValueValidator(limit_value=1)])),
                ('review_date', models.DateField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.movie')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
