# Generated by Django 4.1.7 on 2023-03-15 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=10), django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
